const jobTitles = [
    'Accountant',
    'Administrative Assistant',
    'Backend Developer',
    'Business Analyst',
    'Civil Engineer',
    'Cloud Engineer',
    'Content Writer',
    'Customer Service Executive',
    'Cybersecurity Analyst',
    'Data Analyst',
    'Data Engineer',
    'Data Scientist',
    'Digital Marketing Executive',
    'Electrical Engineer',
    'Finance Executive',
    'Frontend Developer',
    'Full Stack Developer',
    'Graphic Designer',
    'Human Resource Executive',
    'IT Support Specialist',
    'Legal Executive',
    'Marketing Executive',
    'Mechanical Engineer',
    'Mechatronics Engineer',
    'Mobile App Developer',
    'Network Engineer',
    'Operations Executive',
    'Product Manager',
    'Project Manager',
    'Quality Assurance Engineer',
    'Recruitment Consultant',
    'Sales Executive',
    'Senior Backend Developer',
    'Senior Data Analyst',
    'Senior Network Engineer',
    'Senior Software Engineer',
    'Software Engineer',
    'Solutions Architect',
    'System Administrator',
    'UI/UX Designer',
    'Web Developer'
];

const locations = [
    'Johor, Malaysia',
    'Kedah, Malaysia',
    'Kelantan, Malaysia',
    'Kuala Lumpur, Malaysia',
    'Labuan, Malaysia',
    'Melaka, Malaysia',
    'Negeri Sembilan, Malaysia',
    'Pahang, Malaysia',
    'Penang, Malaysia',
    'Perak, Malaysia',
    'Perlis, Malaysia',
    'Putrajaya, Malaysia',
    'Sabah, Malaysia',
    'Sarawak, Malaysia',
    'Selangor, Malaysia',
    'Terengganu, Malaysia'
];

const skills = [
    'A/B Testing',
    'Adobe Illustrator',
    'Adobe Photoshop',
    'Adobe XD',
    'Agile',
    'Amazon Web Services (AWS)',
    'Analytics',
    'Angular',
    'AutoCAD',
    'Automotive Engineering Technology',
    'AWS',
    'Azure',
    'Bootstrap',
    'C#',
    'C++',
    'CAD for Mechatronics',
    'Canva',
    'CI/CD',
    'Communication',
    'Content Marketing',
    'CSS',
    'Customer Service',
    'Data Analysis',
    'Design Patterns',
    'Docker',
    'Elasticsearch',
    'Excel',
    'Express',
    'Figma',
    'Financial Analysis',
    'Flutter',
    'GCP',
    'Git',
    'Google Analytics',
    'Graphic Design',
    'HTML',
    'Illustrator',
    'Java',
    'JavaScript',
    'Kotlin',
    'Kubernetes',
    'Leadership',
    'Linux',
    'Machine Learning',
    'Mechatronics System Integration',
    'Microsoft Azure',
    'Microsoft Office',
    'MongoDB',
    'MySQL',
    'Next.js',
    'Node.js',
    'PHP',
    'Photoshop',
    'PostgreSQL',
    'Power BI',
    'Project Management',
    'Prototyping',
    'Python',
    'React',
    'Redis',
    'REST APIs',
    'Robotics and Automation',
    'Ruby',
    'Sales',
    'SAP',
    'Sass',
    'Scrum',
    'Search Engine Optimisation (SEO)',
    'SEO',
    'Sketch',
    'Spring Boot',
    'SQL',
    'Tableau',
    'Tailwind',
    'Teamwork',
    'TypeScript',
    'UI/UX Design',
    'UX Research',
    'Vue',
    'Vue.js'
];

const experienceLevels = [
    'No experience required',
    'Internship experience',
    'Less than 1 year',
    '1-2 years',
    '3-5 years',
    '6-8 years',
    '9-10 years',
    'More than 10 years'
];

const employmentTypes = [
    'Full-Time',
    'Part-Time',
    'Contract',
    'Temporary',
    'Internship'
];

const educationLevels = [
    'No formal qualification',
    'SPM / O-Level',
    'Certificate',
    'Diploma',
    "Bachelor's Degree",
    "Master's Degree",
    'Doctorate'
];

module.exports = {
    jobTitles,
    locations,
    skills,
    experienceLevels,
    employmentTypes,
    educationLevels
};
